Adapt w.r.t. coq/coq#17824.
QuickChick/QuickChick pull request #335
Opened 2023-07-07 14:53 UTC by ppedrot

2023-07-09 16:47 UTC, liyishuai requested changes
Please wrap the changes with `#if COQ_VERSION >= (8, 18, 0)` (or the proper Coq version). See three lines below for the Cppo syntax.

2023-07-10 11:20 UTC, SkySkimmer commented
Please merge

2023-07-11 11:11 UTC, SkySkimmer commented on plugin/tactic_quickchick.mlg.cppo
> +#if COQ_VERSION >= (8, 18, 0)
```suggestion
#if COQ_VERSION >= (8, 19, 0)
```

2023-07-12 05:23 UTC, liyishuai approved these changes

2023-07-12 05:45 UTC, merged