Basic quickchick tactic for use during proofs
QuickChick/QuickChick pull request #348
Opened 2023-12-18 17:49 UTC by segevem

Adds a tactic for Quickchecking the current proof goal in a naive fashion, using default generators for all variables and checking and filtering inputs against the hypotheses.

2023-12-19 04:07 UTC, liyishuai commented
The CI is failing. Which version of Coq are you working on?
If backwards compatibility requires excessive effort, maybe worth dropping support for some old versions of Coq.

2023-12-19 13:46 UTC, Lysxia commented
This looks impressive!

2023-12-19 17:53 UTC, segevem commented
> The CI is failing. Which version of Coq are you working on? If backwards compatibility requires excessive effort, maybe worth dropping support for some old versions of Coq.

The CI was failing due to some warnings I had to resolve, I'm using Coq 8.17.0

2023-12-20 02:07 UTC, segevem commented
Discovered why the Opam dev test for this branch and master are still failing: in examples/stlc/verif.v, there is a use of Arith.Max.le_max_l and Arith.Max.le_max_r. Arith.Max was deprecated in coq 8.16.0 and appears to have been removed in coq dev. 

The intended replacement, PeanoNat.Nat.le_max_l and PeanoNat.Nat.le_max_r, I believe are in all versions from 8.9 onwards. I am going to perform that replacement in this request.

2023-12-22 06:22 UTC, lemonidas commented on plugin/tactic_quickchick.mlg.cppo
> +(*
These should not be commented out.

2023-12-22 06:22 UTC, lemonidas commented on plugin/tactic_quickchick.mlg.cppo
> -  open Stdarg
Re-enable this, once you re-enable the merge-related tactics.

2023-12-22 06:22 UTC, lemonidas commented on plugin/tactic_quickchick.mli
Might be unnecessary once you re-enable the merge-related tactics.

2023-12-22 06:23 UTC, lemonidas requested changes
This looks good - once the merge-related tactics (which seem otherwise untouched) are re-enabled, I'll approve.

2023-12-22 07:00 UTC, lemonidas approved these changes

2023-12-22 07:02 UTC, merged