Change Derive vernacular identifier
QuickChick/QuickChick pull request #388
Opened 2024-09-13 12:24 UTC by 4ever2

QuickChick and Equations cannot be required/imported in the same file in older versions of Coq (<= 8.18) since they both define a `Derive` vernacular using the same id "Derive".
This PR changes it to "QuickChickDerive" to avoid clashes with other plugins defining a `Derive` vernacular.

Related to https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Anomaly.3A.20bad.20vernac.20extend

2024-09-13 12:26 UTC, Lysxia commented
Since there is already `QCDerive` we can just remove the `Derive` variant.

2024-09-13 12:29 UTC, 4ever2 commented
That would break backward compatibility but I can make that change instead if you prefer it.

2024-09-14 02:49 UTC, liyishuai requested changes
The current changes would require the dependants to write their own Cppo commands to adapt to different Coq versions.

Propose releasing a backward-incompatible version of QuickChick, and the dependants only need to specify the QC version.

2024-09-14 09:25 UTC, Lysxia commented
Yeah, renaming `Derive` for Coq < 8.19 already breaks backwards compatibility. It's worth the simplicity to remove `Derive` once for all instead.

2024-09-14 11:41 UTC, 4ever2 commented
Maybe I'm misunderstanding things, but how would this change break backwards compatibility.
I'm not renaming the command just an internal identifier used by Coq. As far as I can tell there are no user facing changes in this PR.

2024-09-14 15:40 UTC, liyishuai commented
> Maybe I'm misunderstanding things, but how would this change break backwards compatibility. I'm not renaming the command just an internal identifier used by Coq. As far as I can tell there are no user facing changes in this PR.

Say I use `Derive` command in my project on old version of Coq, which has nothing to do with the Coq Derive module.
One day I want to compile the same project on multiple versions of Coq, old and new.

Now the new Coq compilation breaks because QuickChick exposes different commands for different versions of Coq.
But on my side, if I'm unaware of this QuickChick feature, I'll doubt that "**my code** is incompatible with the new version of **Coq**", because I can't imagine "**QuickChick** does different things on different Coq".

2024-09-14 16:32 UTC, Lysxia commented
Sorry, I did misunderstand what this is renaming. But then why not also rename it for Coq >= 8.19?

2024-09-14 17:08 UTC, liyishuai commented
Now my main confusion: What motivates the code to diverge between Coq versions?
In most cases, Cppo is to adapt to the different OCaml API between Coq versions. Otherwise, the plugin doesn't typecheck.

2024-09-14 17:26 UTC, 4ever2 commented
> But then why not also rename it for Coq >= 8.19?

In Coq >= 8.19 the identifier is made unique by Coq so the problem doesn't exists in the latest versions. However, I guess it would make the codebase simpler by just changing the name for all versions.

2024-09-14 17:47 UTC, 4ever2 commented
I removed the Cppo usage, and tested that it works with Coq 8.17-8.19

2024-09-14 17:54 UTC, liyishuai approved these changes

2024-09-18 04:16 UTC, merged